export enum PRDBSupportedLanguage {
  AR = 'ar', // Arabic
  BG = 'bg', // Bulgarian
  CS = 'cs', // Czech
  DA = 'da', // Danish
  DE = 'de', // German
  EL = 'el', // Greek
  ES = 'es', // Spanish
  ET = 'et', // Estonian
  FI = 'fi', // Finnish
  FR = 'fr', // French
  HU = 'hu', // Hungarian
  ID = 'id', // Indonesian
  IT = 'it', // Italian
  JA = 'ja', // Japanese
  KO = 'ko', // Korean
  LT = 'lt', // Lithuanian
  LV = 'lv', // Latvian
  NB = 'nb', // Norwegian Bokmål
  NL = 'nl', // Dutch
  PL = 'pl', // Polish
  RO = 'ro', // Romanian
  RU = 'ru', // Russian
  SK = 'sk', // Slovak
  SL = 'sl', // Slovenian
  SV = 'sv', // Swedish
  TR = 'tr', // Turkish
  UK = 'uk', // Ukrainian
  ZH = 'zh', // Chinese
  EN = 'en', // English
  PT = 'pt', // Portuguese
}
