name: Continuous Integration

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - feature/**
      - hotfix/**
      - bugfix/**
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:
    branches:
      - main
      - feature/**
      - hotfix/**
      - bugfix/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Typescript
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Cache build output
        uses: actions/cache@v4
        with:
          path: dist
          key: ${{ runner.os }}-dist-${{ github.sha }}

  test:
    name: Test (${{ matrix.node }})
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        node: ['22', '20', '18']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Restore build output
        uses: actions/cache@v4
        with:
          path: dist
          key: ${{ runner.os }}-dist-${{ github.sha }}

      - name: Test
        run: npm test

  publish:
    name: Publish
    if: >-
      (github.event_name == 'workflow_dispatch' || github.event_name == 'push') &&
      startsWith(github.ref, 'refs/tags/v')
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Restore build output
        uses: actions/cache@v4
        with:
          path: dist
          key: ${{ runner.os }}-dist-${{ github.sha }}

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
